Migrate to pint_models package
SUSE-Enceladus/public-cloud-info-service pull request #143
Opened 2024-11-01 18:53 UTC by smarlowucf

Moving shared models and database utitilities to a separate package.

2024-11-01 18:56 UTC, rtamalin commented
Code looks good but checks are failing

2024-11-01 18:58 UTC, rtamalin commented
Looks like the pint-models package doesn't support older Python versions, and this package doesn't support newer ones ;-)

2024-11-01 18:59 UTC, rtamalin approved these changes
LGTM - but there are check pipeline issues to resolve ;-)

2024-11-01 19:46 UTC, rjschwei requested changes

2024-11-01 19:46 UTC, rjschwei commented on pint_server/app.py
> +from pint_modesl.database import init_db, get_psql_server_version
s/pint_modesl/pint_models/

2024-11-01 20:05 UTC, smarlowucf commented
> Code looks good but checks are failing

Yep, after a bit of digging I realize that pyproject.toml wasn't supported in python 3.6. So the pint_models package needs to be reverted to setup.py until 3.6 support is dropped. Or pint server code drops support for python 3.6.

2024-11-01 20:18 UTC, rjschwei commented
I do not really see a reason why pint cannot/does not run on Python 3.11

2024-11-01 20:21 UTC, jeremy-moffitt commented
> I do not really see a reason why pint cannot/does not run on Python 3.11

we just need to test it and update the deployment... we've kicked the can a few times on this one, looks like it finally caught up with us :-/

2024-11-01 23:16 UTC, rtamalin commented
@rjschwei IIRC I have run it under Python 3.10 or 3.11, so the code itself should run fine, but the setup.py needs to be updated to reflect that, and we need to redo the container and associated package builds to use the python311 ecosystem; right now it is using the SLE 15 stream default python ecosystem, i.e. Python 3.6 :-(

2024-11-06 17:44 UTC, rjschwei approved these changes

2024-11-06 17:45 UTC, rjschwei commented
> I assume it would take some time to migrate to 3.11. Is it better to revert the public-cloud-info-models package to use setup.py temporarily until this can happen? That way the PR's aren't all stuck waiting?

That should be a matter of changing the spec file and setup.py, meaning probably not more than 1 hours worth of work.

2024-11-06 19:22 UTC, merged